apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace : apache
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: devopsengineering/apache:1
        ports:
        - containerPort: 80
